config/routes.rb
AmoebaCircus::Application.routes.draw do
  root 'pages#index'
  resources :amoebas, :only => [:edit, :update, :destroy, :show, :index]
  resources :acts

  post '/amoebas/:id/split' => 'amoebas#split'

end

app/models/act.rb
class Act < ActiveRecord::Base
  has_many :amoeba_acts
  has_many :amoebas, :through => :amoeba_acts
  accepts_nested_attributes_for :amoebas
  validates :name, presence: true
end

app/models/amoeba.rb
class Amoeba < ActiveRecord::Base
  NAMES = %w[Bob Dave Alice Jenny Loafy Piper Channing Carol Fear&Loathing Paul Smithy Thompson Yonks Mew Mewtwo Pikachu Agdubs Ari Jonathan Grover Oscar YewTree]

  has_one :talent
  has_many :amoeba_acts
  has_many :acts, :through => :amoeba_acts
  accepts_nested_attributes_for :acts
  validates :name, presence: true

  def mitosis
    first_child = Amoeba.create(name: names.sample, generation: self.generation + 1, talent_id: self.talent_id)

    second_child = Amoeba.create(name: names.sample, generation: self.generation + 1, talent_id: self.talent_id)

    self.acts.each do |act|
      act.amoebas << first_child << second_child
    end

    self.destroy
  end

  def names
    NAMES.drop_while {|name| name == self.name}
  end

  def generation_number
    generation = self.generation.to_s
    if /1$/.match(generation)
      generation + "st"
    elsif /2$/.match(generation)
      generation + "nd"
    elsif /3$/.match(generation)
      generation + "rd"
    else
      generation + "th"
    end
  end
end

app/models/amoeba_act.rb
class AmoebaAct < ActiveRecord::Base
  belongs_to :act
  belongs_to :amoeba
end

app/models/talent.rb
class Talent < ActiveRecord::Base
  has_many :amoebas
  validates :name, presence: true
end

app/controllers/acts_controller.rb
class ActsController < ApplicationController
  def index
    @acts = Act.all
  end

  def show
    @act = Act.find(params[:id])
  end

  def new
    @act = Act.new
  end

  def create
    @act = Act.new(act_params)
    if @act.save
      redirect_to @act
    else
      render 'new'
    end
  end

  def edit
    @act = Act.find(params[:id])
  end

  def update
    @act = Act.find(params[:id])
    if @act.update_attributes(act_params)
      redirect_to @act
    else
      render 'edit'
    end
  end

  def destroy
    Act.find(params[:id]).destroy
    redirect_to acts_path
  end

  private
    def act_params
      params.require(:act).permit(:name, :time, :date, :amoeba_ids => [])
    end
end

app/controllers/amoebas_controller.rb
class AmoebasController < ApplicationController
  def index
    @amoebas = Amoeba.all
  end

  def show
    @amoeba = Amoeba.find(params[:id])
  end

  def new
    @amoeba = Amoeba.new
  end

  def split
    Amoeba.find(params[:id]).mitosis

    redirect_to amoebas_path
  end

  def create
    @amoeba = Amoeba.new(amoeba_params)
    if @amoeba.save
      redirect_to @amoeba
    else
      render 'new'
    end
  end

  def edit
    @amoeba = Amoeba.find(params[:id])
  end

  def update
    @amoeba = Amoeba.find(params[:id])
    if @amoeba.update_attributes(amoeba_params)
      redirect_to @amoeba
    else
      render 'edit'
    end
  end

  def destroy
    Amoeba.find(params[:id]).destroy
    redirect_to amoebas_path
  end

  private
    def amoeba_params
      params.require(:amoeba).permit(:name, :talent_id, :first_child, :second_child, :generation, :act_ids => [])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/acts_helper.rb
module ActsHelper
end

app/helpers/amoebas_helper.rb
module AmoebasHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/acts/_act.haml
%p= link_to act.name, act

app/views/acts/_form.haml
= form_for @act do |f|
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :date
    = f.date_select :date
  .field
    = f.label :time
    = f.time_select :time, {:ampm => true}
  .field
    = f.label "Amoebas in this act:"
    = f.collection_check_boxes(:amoeba_ids, Amoeba.all, :id, :name)

  = f.submit 'Submit'

app/views/acts/edit.haml
%h1 Edit Act
= render 'form'

app/views/acts/index.haml
%h1 Amoeba Circus Acts
= render @acts

app/views/acts/new.haml
%h1 New Act
= render 'form'

app/views/acts/show.haml
%h1= @act.name
%p Performing at #{@act.time.strftime("%H:%M")} on #{@act.date}.
%p
  Amoebas:
  %ul
    = render @act.amoebas
%p= link_to 'Change Act Lineup', edit_act_path
%p= link_to 'Back to Circus', root_path

app/views/amoebas/_amoeba.haml
%li #{link_to amoeba.name, amoeba}, #{Talent.find_by_id(amoeba.talent_id).name}

app/views/amoebas/_form.haml
= form_for @amoeba do |f|
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :talent
    = f.collection_select :talent_id, Talent.all, :id, :name
  .field
    = f.label "Acts for this amoeba:"
    = f.collection_check_boxes(:act_ids, Act.all, :id, :name)

  = f.submit 'Submit'

app/views/amoebas/edit.haml
%h1 Edit Amoeba
= render 'form'

app/views/amoebas/index.haml
%h1 Amazing Amoebas
= render @amoebas

app/views/amoebas/new.haml
%h1 New Amoeba
= render 'form'

app/views/amoebas/show.haml
%h1= @amoeba.name
%p #{@amoeba.name} is a talented #{@amoeba.generation_number}-generation #{Talent.find_by_id(@amoeba.talent_id).name}.
- if @amoeba.acts.any?
  %p #{@amoeba.name} performs in the following acts:
  %ul
    - @amoeba.acts.each do |act|
      %li= link_to act.name, act
%p= link_to 'Split Amoeba', "/amoebas/#{@amoeba.id}/split", method: :post, confirm: "Are you sure?"
%p= link_to 'Edit Amoeba', edit_amoeba_path
%p= link_to 'Back to Circus', root_path

app/views/amoebas/split.haml
%h1 Split this amoeba?

= form_tag amoeba_path, method: "post" do |f|
  .field
    = label_tag :first_child, "Name for first new amoeba:"
    = text_field_tag :first_child
  .field
    = label_tag :second_child, "Name for second amoeba:"
    = text_field_tag :second_child
  = submit_tag "Split"

app/views/layouts/application.haml
!!!
%html
  %head
    %title Amoeba Circus
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    .container
      = yield

app/views/pages/dashboard.haml
%h1 Dashboard
%h2 Amoebas:
%ul
  = render Amoeba.all
%h2 Acts
  = render Act.all

app/views/pages/index.haml
%h1 THE AMAZING AMOEBA CIRCUS
%h2= link_to 'The Acts', acts_path
%h2= link_to 'The Amoebas', amoebas_path